export { default as FeaturedProperties } from './FeaturedProperties/FeaturedProperties';
export { default as PropertyList } from './PropertyList/PropertyList';
export { default as SearchItem } from './SearchItem/SearchItem';
export { default as Featured } from './Featured/Featured';
export { default as MailList } from './MailList/MailList';
export { default as Booking } from './Booking/Booking';
export { default as Navbar } from './Navbar/Navbar';
export { default as Header } from './Header/Header';
export { default as Footer } from './Footer/Footer';